### PR TITLE
add support for using in browser

### PR DESCRIPTION
**Pull request by HardCoreQual**
remove fs & path to make code able to be executed in the browser

PS: Great library, I use it here https://joi-to-zod.vercel.app/

### CODE REVIEW

**Comment by HardCoreQual** [comment]
also think I should mention that in browser Joi don't have describe for minimize build code,  in order to have Joi that has describe you should use
```typescript
import Joi from 'joi/lib/index';
```

**Comment by kenspirit** [comment]
> also think I should mention that in browser Joi don't have describe for minimize build code, in order to have Joi that has describe you should use
> 
> ```ts
> import Joi from 'joi/lib/index';
> ```
> 
> for create your schemas that is able to be converted

Thanks for the PR and kindly reminder.  I think it would be nice if you can also put this into the README if you do not mind.

**Comment by HardCoreQual** [comment]
I don't know English very good, and not sure that I write the correct sentence for readme.

**Comment by kenspirit** [comment]
Version 2.5.0 is released

**Pull request merged**
